GET http://localhost:8888/api/customers
Authorization: Bearer CfDJ8GZV-3Ghk6BDjcYpoRwcMjNImwIY36p35cciAzINqzuDVFYGjSIxCRgnbAIORhsehgTOgJSjIKF3_NRH8_dbFpNQHvX-qiyyKk1ezoTBoqkD2o_Z1FK01uYYKxDkB9svCNt1pI4yGMX1HBwQeKt-0vL0mNva28Azj2Wmqmf2cjI_A29UJAgMUfGL6ohscDHvqXxGgV9lvHoPxEsTg1XuvTEF2ktd4cm8o7b8cldI-XlTtAlChKd4INoaETwdOmtpJRPry6bglbTNW0ewuJxarfV6sWNN6f-IRV7uEEBEvfDU9CKSOyY5bk6vzluSpt2JGxDzfrWL4Ec3i79AV3WC9ASV_kdfeXcRCeKmCKjcuRRlTFpLOfACPw3mCfz4F-z_ZP1N7fBK5Tr-CiSc02zTFEeBDmYHok5YTSAnUPg5HGe_uYptnRKPiNqezAOjtj_CoGnFBCMAFbIIq__oyz1EfrnCOs56DBjqcAngqdUXg5784MLiQZmo5ipy9QT0ub0OHVCkDUEYa28ENbJYvsW9Ckkvppv1FVjYVSLX-7Jz8NDNFMIJMOWlyXOqNXefKaOhZ2RAChIYfjzl2r3mOehie8ea4hrqJssPQ2mxcF-vQAJhmtBDXQV2DC8QBwouXXqzWX08iNScg2nodz7xgGywi4xX3OgalEIlTC630ngr0pzZYP8BCRDPrKJgL5LZ3qWpDQ

###

GET http://localhost:8888/api/customers?withAddresses=true

###

GET http://localhost:8888/api/customers/20

###

GET http://localhost:8888/api/timebills/4
Authorization: Bearer CfDJ8GZV-3Ghk6BDjcYpoRwcMjP8IuR2JVScWLF2vPvcRUmqzP0Hs6dgBKWOiXARXN86IUibWvZylO9bUiiNwRYzbIjuPNkJZ7F6oKD09YtJELriIZe-em09dwQirF08iXXayjz-LJJXTBcgyCynJ5pngsqvjyvKIfJjkvfgdStAHUunmWAO6SQemBxkVnA-kTGU88Mtvh_nuWhAb4uMcPGjRAK1XVit1O6RC5nEDHfOC2Wo4TeLE11CMBqxqktvh4fTe5tMjnu5g2JswQP5VAtu_344r8QqofUvKz6-mmivdIPthTM4e_JNO1H58afdblT5Gpy_vMqhSB6EMav9RPNt7GXzcvhtXF1ahjzG5CZYM3R7M-UArdBFVAbDJUz9cXgqddaaxEekjR4pUEahLWKFMj6DwW4N79WOO59xDS0BmCufuceNNY-pISycR-jAZ1JrnGtt-fYYIWXHo7ZkDL-TzLO7ABBL1ulMXUNnL3nUpWddw48boJZ7NgjFhPSD3RF-5gu6gMwLhvKV_OVyUN_iNTZS6IQsfzhvLbZ-1Otb5QVJkoEwl1-Zmn60WvIfZkITqpOn2fHRTA6Um_81WZkYLzPe-n8VZMcznQFtnuT4BzuKz6JVQhqfLu-dfyKu6zUr9E3NLQXiXI7XsdQUtBAKyfnqWelN1doHWZdTaMKg7UqrMGehQcunTeneioDVjfqLjw

###

POST http://localhost:8888/api/timebills
Content-Type: application/json
Authorization: Bearer CfDJ8GZV-3Ghk6BDjcYpoRwcMjP8IuR2JVScWLF2vPvcRUmqzP0Hs6dgBKWOiXARXN86IUibWvZylO9bUiiNwRYzbIjuPNkJZ7F6oKD09YtJELriIZe-em09dwQirF08iXXayjz-LJJXTBcgyCynJ5pngsqvjyvKIfJjkvfgdStAHUunmWAO6SQemBxkVnA-kTGU88Mtvh_nuWhAb4uMcPGjRAK1XVit1O6RC5nEDHfOC2Wo4TeLE11CMBqxqktvh4fTe5tMjnu5g2JswQP5VAtu_344r8QqofUvKz6-mmivdIPthTM4e_JNO1H58afdblT5Gpy_vMqhSB6EMav9RPNt7GXzcvhtXF1ahjzG5CZYM3R7M-UArdBFVAbDJUz9cXgqddaaxEekjR4pUEahLWKFMj6DwW4N79WOO59xDS0BmCufuceNNY-pISycR-jAZ1JrnGtt-fYYIWXHo7ZkDL-TzLO7ABBL1ulMXUNnL3nUpWddw48boJZ7NgjFhPSD3RF-5gu6gMwLhvKV_OVyUN_iNTZS6IQsfzhvLbZ-1Otb5QVJkoEwl1-Zmn60WvIfZkITqpOn2fHRTA6Um_81WZkYLzPe-n8VZMcznQFtnuT4BzuKz6JVQhqfLu-dfyKu6zUr9E3NLQXiXI7XsdQUtBAKyfnqWelN1doHWZdTaMKg7UqrMGehQcunTeneioDVjfqLjw
{
  "hoursWorked": 3.0,
  "Rate": 100.00,
  "date": "2023-06-11",
  "work": "I did a thing...",
  "customerId": 1,
  "employeeId": 1
}

###

GET http://localhost:8888/api/customers/1/timebills

###

GET http://localhost:8888/api/customers/1/timebills/8

###

POST http://localhost:8888/api/auth/login
Content-Type: application/json
{
  "email": "blabla@jajaja.com",
  "password": "Carlitos_01"
}